//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace EndlessModding.EndlessSpace2.Common.Classes.ContextualDiplomaticTermDefinition
{

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiplomaticAbilityWhenActive
    {

        private string nameField;

        private ApplicationMode applyOnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ApplicationMode ApplyOn
        {
            get
            {
                return this.applyOnField;
            }
            set
            {
                this.applyOnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ApplicationMode
    {

        /// <remarks/>
        Symmetrical,

        /// <remarks/>
        FirstEmpireTowardsSecondEmpire,

        /// <remarks/>
        SecondEmpireTowardsFirstEmpire,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConstructionCost
    {

        private bool instantField;

        private bool instantOnCompletionField;

        private string resourceNameField;

        private float valueField;

        public ConstructionCost()
        {
            this.instantField = false;
            this.instantOnCompletionField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Instant
        {
            get
            {
                return this.instantField;
            }
            set
            {
                this.instantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool InstantOnCompletion
        {
            get
            {
                return this.instantOnCompletionField;
            }
            set
            {
                this.instantOnCompletionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomConstructionCost
    {

        private bool instantField;

        private bool instantOnCompletionField;

        private string resourceNameField;

        private string valueField;

        public CustomConstructionCost()
        {
            this.instantField = false;
            this.instantOnCompletionField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Instant
        {
            get
            {
                return this.instantField;
            }
            set
            {
                this.instantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool InstantOnCompletion
        {
            get
            {
                return this.instantOnCompletionField;
            }
            set
            {
                this.instantOnCompletionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TributeDefinition
    {

        private string resourceNameField;

        private int percentageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Percentage
        {
            get
            {
                return this.percentageField;
            }
            set
            {
                this.percentageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlNamedReference
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_CancelLeechActions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_DisplaySubEffects))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RemoveFleetsFromInfluence))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RemoveNeighbours))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RemoveSpaceRoots))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RemoveTimeBubbles))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ResetEmpireHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ResetInfluenceConversion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ResetPressure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RestrictInteraction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RestrictAttack))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_TransferDiplomaticResource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermSubDynamicEffect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ApplyDiplomaticPressureEffect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTerm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_HeroLock))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_MinorFactionTransfer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_PopulationMigration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ApplyTemporaryEffect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect
    {

        private bool hiddenField;

        private string guiCategoryField;

        public ContextualDiplomaticTermEffect()
        {
            this.hiddenField = false;
            this.guiCategoryField = "CategoryTreaty";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("CategoryTreaty")]
        public string GuiCategory
        {
            get
            {
                return this.guiCategoryField;
            }
            set
            {
                this.guiCategoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_CancelLeechActions : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_DisplaySubEffects : ContextualDiplomaticTermEffect
    {

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RemoveFleetsFromInfluence : ContextualDiplomaticTermEffect
    {

        private Prerequisite[] itemsField;

        private MetaPrerequisite[] metaPrerequisiteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MetaPrerequisite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaPrerequisite[] MetaPrerequisite
        {
            get
            {
                return this.metaPrerequisiteField;
            }
            set
            {
                this.metaPrerequisiteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterpreterPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SupportPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterpreterPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathValidityPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameSettingPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatePrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Prerequisite
    {

        private bool invertedField;

        private string flagsField;

        private string valueField;

        public Prerequisite()
        {
            this.invertedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inverted
        {
            get
            {
                return this.invertedField;
            }
            set
            {
                this.invertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SupportPrerequisite : Prerequisite
    {

        private string politicsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Politics
        {
            get
            {
                return this.politicsField;
            }
            set
            {
                this.politicsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyPrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathValidityPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyPrerequisite : PathValidityPrerequisite
    {

        private bool unlockHiddenField;

        public TechnologyPrerequisite()
        {
            this.unlockHiddenField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UnlockHidden
        {
            get
            {
                return this.unlockHiddenField;
            }
            set
            {
                this.unlockHiddenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameSettingPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatePrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetaPrerequisite
    {

        private Prerequisite[] itemsField;

        private PrerequisiteOperator operatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatePrerequisite", typeof(DatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GameSettingPrerequisite", typeof(GameSettingPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SupportPrerequisite", typeof(SupportPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrerequisiteOperator Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PrerequisiteOperator
    {

        /// <remarks/>
        Or,

        /// <remarks/>
        And,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RemoveNeighbours : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RemoveSpaceRoots : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RemoveTimeBubbles : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_ResetEmpireHistory : ContextualDiplomaticTermEffect
    {

        private bool resetAttackField;

        private bool resetColonizationField;

        private bool resetHackingField;

        public ContextualDiplomaticTermEffect_ResetEmpireHistory()
        {
            this.resetAttackField = false;
            this.resetColonizationField = false;
            this.resetHackingField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ResetAttack
        {
            get
            {
                return this.resetAttackField;
            }
            set
            {
                this.resetAttackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ResetColonization
        {
            get
            {
                return this.resetColonizationField;
            }
            set
            {
                this.resetColonizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ResetHacking
        {
            get
            {
                return this.resetHackingField;
            }
            set
            {
                this.resetHackingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_ResetInfluenceConversion : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_ResetPressure : ContextualDiplomaticTermEffect
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_RestrictAttack))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RestrictInteraction : ContextualDiplomaticTermEffect
    {

        private int durationField;

        private string propertyNameField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_RestrictAttack : ContextualDiplomaticTermEffect_RestrictInteraction
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_TransferDiplomaticResource : ContextualDiplomaticTermEffect
    {

        private TargetType targetField;

        private string resourceNameField;

        private float amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TargetType Target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TargetType
    {

        /// <remarks/>
        EmpireWithChoice,

        /// <remarks/>
        OtherEmpire,

        /// <remarks/>
        Both,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ApplyDiplomaticPressureEffect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTerm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_HeroLock))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_MinorFactionTransfer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermDynamicEffect_PopulationMigration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermEffect_ApplyTemporaryEffect))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermSubDynamicEffect : ContextualDiplomaticTermEffect
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_ApplyDiplomaticPressureEffect : ContextualDiplomaticTermSubDynamicEffect
    {

        private XmlNamedReference diplomaticPressureEffectReferenceField;

        private DiplomaticEffectTargetType targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference DiplomaticPressureEffectReference
        {
            get
            {
                return this.diplomaticPressureEffectReferenceField;
            }
            set
            {
                this.diplomaticPressureEffectReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DiplomaticEffectTargetType Target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum DiplomaticEffectTargetType
    {

        /// <remarks/>
        CurrentEmpire,

        /// <remarks/>
        CurrentEmpireOnOtherEmpires,

        /// <remarks/>
        OtherEmpireOnOtherEmpires,

        /// <remarks/>
        CurrentEmpireOnOtherEmpiresAndOtherEmpire,

        /// <remarks/>
        OtherEmpireOnOtherEmpiresAndChooserEmpire,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect_DiplomaticTerm : ContextualDiplomaticTermSubDynamicEffect
    {

        private XmlNamedReference[] diplomaticTermReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticTermReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference[] DiplomaticTermReference
        {
            get
            {
                return this.diplomaticTermReferenceField;
            }
            set
            {
                this.diplomaticTermReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect_DiplomaticTribute : ContextualDiplomaticTermSubDynamicEffect
    {

        private TributeDefinition[] tributeField;

        private int durationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tribute", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TributeDefinition[] Tribute
        {
            get
            {
                return this.tributeField;
            }
            set
            {
                this.tributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect_HeroLock : ContextualDiplomaticTermSubDynamicEffect
    {

        private int durationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect_MinorFactionTransfer : ContextualDiplomaticTermSubDynamicEffect
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect_PopulationMigration : ContextualDiplomaticTermSubDynamicEffect
    {

        private int populationCountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PopulationCount
        {
            get
            {
                return this.populationCountField;
            }
            set
            {
                this.populationCountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermEffect_ApplyTemporaryEffect : ContextualDiplomaticTermSubDynamicEffect
    {

        private XmlNamedReference temporaryEffectReferenceField;

        private TemporaryEffectTargetType targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference TemporaryEffectReference
        {
            get
            {
                return this.temporaryEffectReferenceField;
            }
            set
            {
                this.temporaryEffectReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TemporaryEffectTargetType Target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TemporaryEffectTargetType
    {

        /// <remarks/>
        CurrentEmpire,

        /// <remarks/>
        OtherEmpire,

        /// <remarks/>
        Context,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermDynamicEffect : ContextualDiplomaticTermEffect
    {

        private ContextualDiplomaticTermSubDynamicEffect[] itemsField;

        private string nameField;

        private ApplicationMethod applicationMethodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Effect_DiplomaticEffect", typeof(ContextualDiplomaticTermEffect_ApplyDiplomaticPressureEffect), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_DiplomaticTerm", typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTerm), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_DiplomaticTribute", typeof(ContextualDiplomaticTermDynamicEffect_DiplomaticTribute), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_HeroLock", typeof(ContextualDiplomaticTermDynamicEffect_HeroLock), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_MinorFactionTransfer", typeof(ContextualDiplomaticTermDynamicEffect_MinorFactionTransfer), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_PopulationMigration", typeof(ContextualDiplomaticTermDynamicEffect_PopulationMigration), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_TemporaryEffect", typeof(ContextualDiplomaticTermEffect_ApplyTemporaryEffect), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContextualDiplomaticTermSubDynamicEffect[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ApplicationMethod ApplicationMethod
        {
            get
            {
                return this.applicationMethodField;
            }
            set
            {
                this.applicationMethodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ApplicationMethod
    {

        /// <remarks/>
        ReceiverOnly,

        /// <remarks/>
        ProviderOnly,

        /// <remarks/>
        Symmetrical,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermChoice
    {

        private Prerequisite[] itemsField;

        private MetaPrerequisite[] metaPrerequisiteField;

        private object[] items1Field;

        private ContextualDiplomaticTermEffect[] items2Field;

        private XmlNamedReference resultingTermReferenceField;

        private XmlNamedReference[] populationEventField;

        private object[] items3Field;

        private bool isPositiveField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatePrerequisite", typeof(DatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GameSettingPrerequisite", typeof(GameSettingPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MetaPrerequisite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaPrerequisite[] MetaPrerequisite
        {
            get
            {
                return this.metaPrerequisiteField;
            }
            set
            {
                this.metaPrerequisiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticAbilityPrerequisite", typeof(DiplomaticAbilityPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticMetaPrerequisite", typeof(SimpleDiplomaticMetaPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticRelationStatePrerequisite", typeof(DiplomaticRelationStatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DynamicEffect", typeof(ContextualDiplomaticTermDynamicEffect), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_ApplyDiplomaticEffect", typeof(ContextualDiplomaticTermEffect_ApplyDiplomaticPressureEffect), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_ApplyTemporaryEffect", typeof(ContextualDiplomaticTermEffect_ApplyTemporaryEffect), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_CancelLeechActions", typeof(ContextualDiplomaticTermEffect_CancelLeechActions), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_DisplaySubEffects", typeof(ContextualDiplomaticTermEffect_DisplaySubEffects), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RemoveFleetsFromInfluence", typeof(ContextualDiplomaticTermEffect_RemoveFleetsFromInfluence), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RemoveNeighbours", typeof(ContextualDiplomaticTermEffect_RemoveNeighbours), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RemoveSpaceRoots", typeof(ContextualDiplomaticTermEffect_RemoveSpaceRoots), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RemoveTimeBubbles", typeof(ContextualDiplomaticTermEffect_RemoveTimeBubbles), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_ResetEmpireHistory", typeof(ContextualDiplomaticTermEffect_ResetEmpireHistory), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_ResetInfluenceConversion", typeof(ContextualDiplomaticTermEffect_ResetInfluenceConversion), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_ResetPressure", typeof(ContextualDiplomaticTermEffect_ResetPressure), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RestrictAttack", typeof(ContextualDiplomaticTermEffect_RestrictAttack), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_RestrictInteraction", typeof(ContextualDiplomaticTermEffect_RestrictInteraction), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Effect_TransferDiplomaticResource", typeof(ContextualDiplomaticTermEffect_TransferDiplomaticResource), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContextualDiplomaticTermEffect[] Items2
        {
            get
            {
                return this.items2Field;
            }
            set
            {
                this.items2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference ResultingTermReference
        {
            get
            {
                return this.resultingTermReferenceField;
            }
            set
            {
                this.resultingTermReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PopulationEvent", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference[] PopulationEvent
        {
            get
            {
                return this.populationEventField;
            }
            set
            {
                this.populationEventField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cost", typeof(ConstructionCost), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("CustomCost", typeof(CustomConstructionCost), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items3
        {
            get
            {
                return this.items3Field;
            }
            set
            {
                this.items3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPositive
        {
            get
            {
                return this.isPositiveField;
            }
            set
            {
                this.isPositiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiplomaticAbilityPrerequisite : DiplomaticPrerequisite
    {

        private PrerequisiteTargetRelation targetRelationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrerequisiteTargetRelation TargetRelation
        {
            get
            {
                return this.targetRelationField;
            }
            set
            {
                this.targetRelationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PrerequisiteTargetRelation
    {

        /// <remarks/>
        ReceiverToProvider,

        /// <remarks/>
        ProviderToReceiver,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticRelationStatePrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticAbilityPrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiplomaticPrerequisite
    {

        private bool invertedField;

        private string flagsField;

        private string valueField;

        public DiplomaticPrerequisite()
        {
            this.invertedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inverted
        {
            get
            {
                return this.invertedField;
            }
            set
            {
                this.invertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiplomaticRelationStatePrerequisite : DiplomaticPrerequisite
    {

        private DiplomaticCostResponsible responsibleField;

        public DiplomaticRelationStatePrerequisite()
        {
            this.responsibleField = DiplomaticCostResponsible.EmpireWhichProvides;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DiplomaticCostResponsible.EmpireWhichProvides)]
        public DiplomaticCostResponsible Responsible
        {
            get
            {
                return this.responsibleField;
            }
            set
            {
                this.responsibleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum DiplomaticCostResponsible
    {

        /// <remarks/>
        EmpireWhichProposes,

        /// <remarks/>
        EmpireWhichProvides,

        /// <remarks/>
        EmpireWhichReceives,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimpleDiplomaticMetaPrerequisite
    {

        private DiplomaticPrerequisite[] itemsField;

        private OperatorType operatorField;

        private bool invertedField;

        private string flagsField;

        public SimpleDiplomaticMetaPrerequisite()
        {
            this.invertedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticAbilityPrerequisite", typeof(DiplomaticAbilityPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticRelationStatePrerequisite", typeof(DiplomaticRelationStatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DiplomaticPrerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OperatorType Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inverted
        {
            get
            {
                return this.invertedField;
            }
            set
            {
                this.invertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OperatorType
    {

        /// <remarks/>
        OR,

        /// <remarks/>
        XOR,

        /// <remarks/>
        NOR,

        /// <remarks/>
        AND,

        /// <remarks/>
        NAND,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_FleetsInInfluence))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_Pressure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_SystemsLeeched))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_SystemsRooted))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_SystemsUnderConversion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermCondition_TimeBubblesOnSystems))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_FleetsDestroyed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_NeighboursColonized))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_NeighboursExploited))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_HackingOperationTraced))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_FleetsInInfluence : ContextualDiplomaticTermCondition
    {

        private Prerequisite[] itemsField;

        private MetaPrerequisite[] metaPrerequisiteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MetaPrerequisite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaPrerequisite[] MetaPrerequisite
        {
            get
            {
                return this.metaPrerequisiteField;
            }
            set
            {
                this.metaPrerequisiteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_Pressure : ContextualDiplomaticTermCondition
    {

        private int minimumField;

        private int maximumField;

        public ContextualDiplomaticTermCondition_Pressure()
        {
            this.maximumField = 2147483647;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Minimum
        {
            get
            {
                return this.minimumField;
            }
            set
            {
                this.minimumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(2147483647)]
        public int Maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_SystemsLeeched : ContextualDiplomaticTermCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_SystemsRooted : ContextualDiplomaticTermCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_SystemsUnderConversion : ContextualDiplomaticTermCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermCondition_TimeBubblesOnSystems : ContextualDiplomaticTermCondition
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_FleetsDestroyed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_NeighboursColonized))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_NeighboursExploited))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextualDiplomaticTermConditionTimer_HackingOperationTraced))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermConditionTimer : ContextualDiplomaticTermCondition
    {

        private int maximumDelayField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaximumDelay
        {
            get
            {
                return this.maximumDelayField;
            }
            set
            {
                this.maximumDelayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermConditionTimer_FleetsDestroyed : ContextualDiplomaticTermConditionTimer
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermConditionTimer_NeighboursColonized : ContextualDiplomaticTermConditionTimer
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermConditionTimer_NeighboursExploited : ContextualDiplomaticTermConditionTimer
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContextualDiplomaticTermConditionTimer_HackingOperationTraced : ContextualDiplomaticTermConditionTimer
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class ContextualDiplomaticTermDefinition : DatatableElement
    {

        private Prerequisite[] itemsField;

        private MetaPrerequisite[] metaPrerequisiteField;

        private object[] items1Field;

        private ContextualDiplomaticTermCondition[] items2Field;

        private ContextualDiplomaticTermChoice[] choiceField;

        private DiplomaticAbilityWhenActive[] diplomaticAbilityWhenActiveField;

        private bool isSubtermField;

        private string autoSelectedProviderDynamicEffectField;

        private string defaultChoiceNameField;

        private int cooldownField;

        private WarDeclarationType cancelOnWarDeclarationField;

        public ContextualDiplomaticTermDefinition()
        {
            this.cooldownField = 0;
            this.cancelOnWarDeclarationField = WarDeclarationType.Both;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatePrerequisite", typeof(DatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GameSettingPrerequisite", typeof(GameSettingPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MetaPrerequisite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaPrerequisite[] MetaPrerequisite
        {
            get
            {
                return this.metaPrerequisiteField;
            }
            set
            {
                this.metaPrerequisiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticAbilityPrerequisite", typeof(DiplomaticAbilityPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticMetaPrerequisite", typeof(SimpleDiplomaticMetaPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticRelationStatePrerequisite", typeof(DiplomaticRelationStatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Condition_FleetsDestroyed", typeof(ContextualDiplomaticTermConditionTimer_FleetsDestroyed), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_FleetsInInfluence", typeof(ContextualDiplomaticTermCondition_FleetsInInfluence), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_HackingOperationTraced", typeof(ContextualDiplomaticTermConditionTimer_HackingOperationTraced), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_NeighboursColonized", typeof(ContextualDiplomaticTermConditionTimer_NeighboursColonized), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_NeighboursExploited", typeof(ContextualDiplomaticTermConditionTimer_NeighboursExploited), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_Pressure", typeof(ContextualDiplomaticTermCondition_Pressure), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_SystemsLeeched", typeof(ContextualDiplomaticTermCondition_SystemsLeeched), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_SystemsRooted", typeof(ContextualDiplomaticTermCondition_SystemsRooted), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_SystemsUnderConversion", typeof(ContextualDiplomaticTermCondition_SystemsUnderConversion), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Condition_TimeBubblesOnSystems", typeof(ContextualDiplomaticTermCondition_TimeBubblesOnSystems), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContextualDiplomaticTermCondition[] Items2
        {
            get
            {
                return this.items2Field;
            }
            set
            {
                this.items2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choice", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContextualDiplomaticTermChoice[] Choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiplomaticAbilityWhenActive", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DiplomaticAbilityWhenActive[] DiplomaticAbilityWhenActive
        {
            get
            {
                return this.diplomaticAbilityWhenActiveField;
            }
            set
            {
                this.diplomaticAbilityWhenActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsSubterm
        {
            get
            {
                return this.isSubtermField;
            }
            set
            {
                this.isSubtermField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AutoSelectedProviderDynamicEffect
        {
            get
            {
                return this.autoSelectedProviderDynamicEffectField;
            }
            set
            {
                this.autoSelectedProviderDynamicEffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultChoiceName
        {
            get
            {
                return this.defaultChoiceNameField;
            }
            set
            {
                this.defaultChoiceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Cooldown
        {
            get
            {
                return this.cooldownField;
            }
            set
            {
                this.cooldownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WarDeclarationType.Both)]
        public WarDeclarationType CancelOnWarDeclaration
        {
            get
            {
                return this.cancelOnWarDeclarationField;
            }
            set
            {
                this.cancelOnWarDeclarationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum WarDeclarationType
    {

        /// <remarks/>
        Disabled,

        /// <remarks/>
        SenderOnly,

        /// <remarks/>
        Both,

        /// <remarks/>
        ReceiverOnly,
    }
}