//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace EndlessModding.EndlessSpace2.Common.Classes.DiplomaticPressureEffectDefinitions
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_Turns))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_Systems))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_DiplomaticAbility))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_DiplomaticRelationState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimulationDescriptorReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValueType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimulationDescriptorReference : ValueType
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_Turns))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_Systems))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_DiplomaticAbility))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_DiplomaticRelationState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DiplomaticPressureEffectDefinition : DatatableElement
    {

        private SimulationDescriptorReference[] simulationDescriptorReferenceOnInitiatorField;

        private SimulationDescriptorReference[] simulationDescriptorReferenceOnTargetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimulationDescriptorReferenceOnInitiator", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SimulationDescriptorReferenceOnInitiator
        {
            get
            {
                return this.simulationDescriptorReferenceOnInitiatorField;
            }
            set
            {
                this.simulationDescriptorReferenceOnInitiatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimulationDescriptorReferenceOnTarget", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SimulationDescriptorReferenceOnTarget
        {
            get
            {
                return this.simulationDescriptorReferenceOnTargetField;
            }
            set
            {
                this.simulationDescriptorReferenceOnTargetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DiplomaticPressureEffectDefinition_DiplomaticRelationState : DiplomaticPressureEffectDefinition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DiplomaticPressureEffectDefinition_DiplomaticAbility : DiplomaticPressureEffectDefinition
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiplomaticPressureEffectDefinition_Systems))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DiplomaticPressureEffectDefinition_Turns : DiplomaticPressureEffectDefinition
    {

        private int durationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DiplomaticPressureEffectDefinition_Systems : DiplomaticPressureEffectDefinition_Turns
    {

        private SimulationDescriptorReference[] systemDescriptorField;

        private SimulationDescriptorReference[] fleetDescriptorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemDescriptor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SystemDescriptor
        {
            get
            {
                return this.systemDescriptorField;
            }
            set
            {
                this.systemDescriptorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FleetDescriptor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] FleetDescriptor
        {
            get
            {
                return this.fleetDescriptorField;
            }
            set
            {
                this.fleetDescriptorField = value;
            }
        }
    }
}