//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace EndlessModding.EndlessSpace2.Common.Classes.ModuleDefinition
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeaponTargetingSortingCriterionScoreModifier {

        private string nameField;

        private float valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeaponTargetSortingCriterionDefinition_PropertyMultiplier))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeaponTargetSortingCriterionDefinition {

        private WeaponTargetingSortingCriterionScoreModifier[] scoreModifierField;

        private string nameField;

        private float scoreModifiersDefaultValueField;

        private bool ignoredWhenCheckingTargetValidityField;

        public WeaponTargetSortingCriterionDefinition() {
            this.scoreModifiersDefaultValueField = ((float)(0F));
            this.ignoredWhenCheckingTargetValidityField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScoreModifier", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WeaponTargetingSortingCriterionScoreModifier[] ScoreModifier {
            get {
                return this.scoreModifierField;
            }
            set {
                this.scoreModifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float ScoreModifiersDefaultValue {
            get {
                return this.scoreModifiersDefaultValueField;
            }
            set {
                this.scoreModifiersDefaultValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoredWhenCheckingTargetValidity {
            get {
                return this.ignoredWhenCheckingTargetValidityField;
            }
            set {
                this.ignoredWhenCheckingTargetValidityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeaponTargetSortingCriterionDefinition_PropertyMultiplier : WeaponTargetSortingCriterionDefinition {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvailableRange {

        private string rangeNameField;

        private float penaltyField;

        private string penaltyPropertyNameField;

        public AvailableRange() {
            this.penaltyField = ((float)(0F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RangeName {
            get {
                return this.rangeNameField;
            }
            set {
                this.rangeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float Penalty {
            get {
                return this.penaltyField;
            }
            set {
                this.penaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PenaltyPropertyName {
            get {
                return this.penaltyPropertyNameField;
            }
            set {
                this.penaltyPropertyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConstructionCost {

        private bool instantField;

        private bool instantOnCompletionField;

        private string resourceNameField;

        private float valueField;

        public ConstructionCost() {
            this.instantField = false;
            this.instantOnCompletionField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Instant {
            get {
                return this.instantField;
            }
            set {
                this.instantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool InstantOnCompletion {
            get {
                return this.instantOnCompletionField;
            }
            set {
                this.instantOnCompletionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomConstructionCost {

        private bool instantField;

        private bool instantOnCompletionField;

        private string resourceNameField;

        private string valueField;

        public CustomConstructionCost() {
            this.instantField = false;
            this.instantOnCompletionField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Instant {
            get {
                return this.instantField;
            }
            set {
                this.instantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool InstantOnCompletion {
            get {
                return this.instantOnCompletionField;
            }
            set {
                this.instantOnCompletionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnlockDatatableElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Module))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SquadronModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BridgeModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MothershipModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogisticsModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefenseModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeaponModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DestructionModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Module))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SquadronModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BridgeModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MothershipModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogisticsModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefenseModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeaponModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DestructionModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnlockDatatableElement : DatatableElement {

        private string keyWordsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KeyWords {
            get {
                return this.keyWordsField;
            }
            set {
                this.keyWordsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SlaveModuleDefinition {

        private string nameField;

        private string categoryForSimulationDescriptorsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoryForSimulationDescriptors {
            get {
                return this.categoryForSimulationDescriptorsField;
            }
            set {
                this.categoryForSimulationDescriptorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlNamedReference {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescriptorEffectProviderWithCategory {

        private SimulationDescriptorReference[] simulationDescriptorReferenceField;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimulationDescriptorReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SimulationDescriptorReference {
            get {
                return this.simulationDescriptorReferenceField;
            }
            set {
                this.simulationDescriptorReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimulationDescriptorReference : ValueType {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimulationDescriptorReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValueType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModuleModifierDefinition {

        private Prerequisite[] itemsField;

        private SimulationDescriptorReference[] simulationDescriptorReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimulationDescriptorReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SimulationDescriptorReference {
            get {
                return this.simulationDescriptorReferenceField;
            }
            set {
                this.simulationDescriptorReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterpreterPrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterpreterPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathValidityPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DownloadableContentPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameSettingPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatePrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Prerequisite {

        private bool invertedField;

        private string flagsField;

        private string valueField;

        public Prerequisite() {
            this.invertedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inverted {
            get {
                return this.invertedField;
            }
            set {
                this.invertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathPrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyPrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathValidityPrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyPrerequisite : PathValidityPrerequisite {

        private bool unlockHiddenField;

        public TechnologyPrerequisite() {
            this.unlockHiddenField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UnlockHidden {
            get {
                return this.unlockHiddenField;
            }
            set {
                this.unlockHiddenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadableContentPrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameSettingPrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatePrerequisite : Prerequisite {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SlotLinkModuleConstraintDefinition {

        private Prerequisite[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkedModuleEffectDefinition {

        private SlotLinkModuleConstraintDefinition linkedModuleConstraintField;

        private ModuleModifierDefinition ownModifierField;

        private ModuleModifierDefinition linkedModuleModifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SlotLinkModuleConstraintDefinition LinkedModuleConstraint {
            get {
                return this.linkedModuleConstraintField;
            }
            set {
                this.linkedModuleConstraintField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModuleModifierDefinition OwnModifier {
            get {
                return this.ownModifierField;
            }
            set {
                this.ownModifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModuleModifierDefinition LinkedModuleModifier {
            get {
                return this.linkedModuleModifierField;
            }
            set {
                this.linkedModuleModifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AIBattleSituation {

        private string situationField;

        private SituationMode modeField;

        private float valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Situation {
            get {
                return this.situationField;
            }
            set {
                this.situationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SituationMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SituationMode {

        /// <remarks/>
        Use,

        /// <remarks/>
        Against,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SquadronModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BridgeModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MothershipModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogisticsModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefenseModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeaponModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DestructionModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Module : UnlockDatatableElement {

        private object[] itemsField;

        private AIBattleSituation[] aIBattleSituationsField;

        private Prerequisite[] items1Field;

        private LinkedModuleEffectDefinition[] linkEffectField;

        private SimulationDescriptorReference[] simulationDescriptorReferenceField;

        private DescriptorEffectProviderWithCategory[] categorizedSimulationDescriptorsField;

        private DescriptorEffectProviderWithCategory[] categorizedSimulationDescriptorsToDisplayField;

        private XmlNamedReference[] battleActionReferenceField;

        private SlaveModuleDefinition[] slaveModuleField;

        private bool isHiddenField;

        private string familyField;

        private int levelField;

        private string guiCategoryField;

        public Module() {
            this.isHiddenField = false;
            this.familyField = "";
            this.levelField = 1;
            this.guiCategoryField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cost", typeof(ConstructionCost), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("CustomCost", typeof(CustomConstructionCost), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AIBattleSituations", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AIBattleSituation[] AIBattleSituations {
            get {
                return this.aIBattleSituationsField;
            }
            set {
                this.aIBattleSituationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatePrerequisite", typeof(DatePrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DownloadableContentPrerequisite", typeof(DownloadableContentPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GameSettingPrerequisite", typeof(GameSettingPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinkEffect", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LinkedModuleEffectDefinition[] LinkEffect {
            get {
                return this.linkEffectField;
            }
            set {
                this.linkEffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimulationDescriptorReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SimulationDescriptorReference {
            get {
                return this.simulationDescriptorReferenceField;
            }
            set {
                this.simulationDescriptorReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategorizedSimulationDescriptors", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DescriptorEffectProviderWithCategory[] CategorizedSimulationDescriptors {
            get {
                return this.categorizedSimulationDescriptorsField;
            }
            set {
                this.categorizedSimulationDescriptorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DescriptorEffectProviderWithCategory[] CategorizedSimulationDescriptorsToDisplay {
            get {
                return this.categorizedSimulationDescriptorsToDisplayField;
            }
            set {
                this.categorizedSimulationDescriptorsToDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BattleActionReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference[] BattleActionReference {
            get {
                return this.battleActionReferenceField;
            }
            set {
                this.battleActionReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SlaveModule", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SlaveModuleDefinition[] SlaveModule {
            get {
                return this.slaveModuleField;
            }
            set {
                this.slaveModuleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsHidden {
            get {
                return this.isHiddenField;
            }
            set {
                this.isHiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string GuiCategory {
            get {
                return this.guiCategoryField;
            }
            set {
                this.guiCategoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DestructionModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class WeaponModule : Module {

        private Prerequisite[] items2Field;

        private XmlNamedReference salvoReferenceField;

        private AvailableRange[] availableRangeField;

        private WeaponTargetSortingCriterionDefinition[] items3Field;

        private WeaponType typeField;

        private int tierField;

        private float lineOfSightOverridenAngleField;

        public WeaponModule() {
            this.tierField = 1;
            this.lineOfSightOverridenAngleField = ((float)(0F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttackInterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AttackPathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AttackTechnologyPrerequisite", typeof(TechnologyPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items2 {
            get {
                return this.items2Field;
            }
            set {
                this.items2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference SalvoReference {
            get {
                return this.salvoReferenceField;
            }
            set {
                this.salvoReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableRange", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AvailableRange[] AvailableRange {
            get {
                return this.availableRangeField;
            }
            set {
                this.availableRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetSortingCriterion", typeof(WeaponTargetSortingCriterionDefinition), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TargetSortingCriterion_PropertyMultiplier", typeof(WeaponTargetSortingCriterionDefinition_PropertyMultiplier), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WeaponTargetSortingCriterionDefinition[] Items3 {
            get {
                return this.items3Field;
            }
            set {
                this.items3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeaponType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int Tier {
            get {
                return this.tierField;
            }
            set {
                this.tierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float LineOfSightOverridenAngle {
            get {
                return this.lineOfSightOverridenAngleField;
            }
            set {
                this.lineOfSightOverridenAngleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum WeaponType {

        /// <remarks/>
        Undefined,

        /// <remarks/>
        Kinetic,

        /// <remarks/>
        Missile,

        /// <remarks/>
        Laser,

        /// <remarks/>
        Beam,

        /// <remarks/>
        Flack,

        /// <remarks/>
        Destruction,

        /// <remarks/>
        AOE,

        /// <remarks/>
        BoardingPod,

        /// <remarks/>
        KineticRailgun,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DefenseModule : Module {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSupportModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MothershipModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogisticsModule))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class SupportModule : Module {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class LogisticsModule : SupportModule {

        private string[] resourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Resource", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class BridgeModule : Module {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class MothershipModule : SupportModule {

        private SimulationDescriptorReference[] systemDescriptorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemDescriptor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SystemDescriptor {
            get {
                return this.systemDescriptorField;
            }
            set {
                this.systemDescriptorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class DestructionModule : WeaponModule {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class SquadronModule : Module {

        private XmlNamedReference stanceSelectorReferenceField;

        private XmlNamedReference defaultFormationReferenceField;

        private string projectilePrefabPathField;

        private string flakProjectilePrefabPathField;

        private SquadronType typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference StanceSelectorReference {
            get {
                return this.stanceSelectorReferenceField;
            }
            set {
                this.stanceSelectorReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference DefaultFormationReference {
            get {
                return this.defaultFormationReferenceField;
            }
            set {
                this.defaultFormationReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProjectilePrefabPath {
            get {
                return this.projectilePrefabPathField;
            }
            set {
                this.projectilePrefabPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlakProjectilePrefabPath {
            get {
                return this.flakProjectilePrefabPathField;
            }
            set {
                this.flakProjectilePrefabPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SquadronType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SquadronType {

        /// <remarks/>
        Fighter,

        /// <remarks/>
        Bomber,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class SystemSupportModule : SupportModule {

        private SimulationDescriptorReference[] systemSimulationDescriptorReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemSimulationDescriptorReference", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SimulationDescriptorReference[] SystemSimulationDescriptorReference {
            get {
                return this.systemSimulationDescriptorReferenceField;
            }
            set {
                this.systemSimulationDescriptorReferenceField = value;
            }
        }
    }
}