//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace EndlessModding.EndlessSpace2.Common.Classes.PopulationEventDefinitions
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlNamedReference
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tags
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationPoliticalEventDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_HappinessChanged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_MothershipDetached))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_DiplomaticAbilityChanged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_AcademyOwnerChanged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_SimulationDescriptorChange))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_StarSystemImprovementCollectionChanged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_HeroAssignationChanged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationEventModifierStoppingCondition_InfluenceStateChanged))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition
    {

        private bool noDecayField;

        public PopulationEventModifierStoppingCondition()
        {
            this.noDecayField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool NoDecay
        {
            get
            {
                return this.noDecayField;
            }
            set
            {
                this.noDecayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_HappinessChanged : PopulationEventModifierStoppingCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_MothershipDetached : PopulationEventModifierStoppingCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_DiplomaticAbilityChanged : PopulationEventModifierStoppingCondition
    {

        private ChangeAction actionField;

        private string diplomaticAbilityNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChangeAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DiplomaticAbilityName
        {
            get
            {
                return this.diplomaticAbilityNameField;
            }
            set
            {
                this.diplomaticAbilityNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ChangeAction
    {

        /// <remarks/>
        Add,

        /// <remarks/>
        Remove,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_AcademyOwnerChanged : PopulationEventModifierStoppingCondition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_SimulationDescriptorChange : PopulationEventModifierStoppingCondition
    {

        private CollectionChangeAction actionField;

        private string descriptorNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CollectionChangeAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DescriptorName
        {
            get
            {
                return this.descriptorNameField;
            }
            set
            {
                this.descriptorNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CollectionChangeAction
    {

        /// <remarks/>
        Add,

        /// <remarks/>
        Remove,

        /// <remarks/>
        Refresh,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_StarSystemImprovementCollectionChanged : PopulationEventModifierStoppingCondition
    {

        private CollectionChangeAction actionField;

        private string improvementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CollectionChangeAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImprovementName
        {
            get
            {
                return this.improvementNameField;
            }
            set
            {
                this.improvementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_HeroAssignationChanged : PopulationEventModifierStoppingCondition
    {

        private HeroAssignationAction actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HeroAssignationAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum HeroAssignationAction
    {

        /// <remarks/>
        Assigned,

        /// <remarks/>
        Unassigned,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopulationEventModifierStoppingCondition_InfluenceStateChanged : PopulationEventModifierStoppingCondition
    {

        private ColonizedInfluenceState stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ColonizedInfluenceState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ColonizedInfluenceState
    {

        /// <remarks/>
        Undefined,

        /// <remarks/>
        None,

        /// <remarks/>
        Owner,

        /// <remarks/>
        OwnerFriend,

        /// <remarks/>
        OwnerFoe,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationPoliticalEventDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class PopulationEventDefinition : DatatableElement
    {

        private PopulationEventModifierStoppingCondition[] itemsField;

        private string categoryField;

        private string subCategoryField;

        private PopulationEventScale scaleField;

        private int durationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_AcademyOwnerChanged", typeof(PopulationEventModifierStoppingCondition_AcademyOwnerChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_DiplomaticAbilityChanged", typeof(PopulationEventModifierStoppingCondition_DiplomaticAbilityChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_HappinessChanged", typeof(PopulationEventModifierStoppingCondition_HappinessChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_HeroAssignationChanged", typeof(PopulationEventModifierStoppingCondition_HeroAssignationChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_InfluenceStateChanged", typeof(PopulationEventModifierStoppingCondition_InfluenceStateChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_MothershipDetached", typeof(PopulationEventModifierStoppingCondition_MothershipDetached), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_SimulationDescriptorChange", typeof(PopulationEventModifierStoppingCondition_SimulationDescriptorChange), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("StoppingCondition_StarSystemImprovementCollectionChanged", typeof(PopulationEventModifierStoppingCondition_StarSystemImprovementCollectionChanged), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PopulationEventModifierStoppingCondition[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubCategory
        {
            get
            {
                return this.subCategoryField;
            }
            set
            {
                this.subCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PopulationEventScale Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PopulationEventScale
    {

        /// <remarks/>
        System,

        /// <remarks/>
        Empire,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class PopulationPoliticalEventDefinition : PopulationEventDefinition
    {

        private Tags tagsField;

        private XmlNamedReference politicsField;

        private float powerField;

        private bool isUniqueField;

        private bool useMainPoliticsDefinitionField;

        public PopulationPoliticalEventDefinition()
        {
            this.isUniqueField = false;
            this.useMainPoliticsDefinitionField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Tags Tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNamedReference Politics
        {
            get
            {
                return this.politicsField;
            }
            set
            {
                this.politicsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Power
        {
            get
            {
                return this.powerField;
            }
            set
            {
                this.powerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsUnique
        {
            get
            {
                return this.isUniqueField;
            }
            set
            {
                this.isUniqueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseMainPoliticsDefinition
        {
            get
            {
                return this.useMainPoliticsDefinitionField;
            }
            set
            {
                this.useMainPoliticsDefinitionField = value;
            }
        }
    }
}