//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace EndlessModding.EndlessSpace2.Common.Classes.SystemDiscoverySequenceDefinition
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlanetoidRadiusFromPlanetSize
    {

        private float radiusField;

        private string planetSizeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Radius
        {
            get
            {
                return this.radiusField;
            }
            set
            {
                this.radiusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlanetSize
        {
            get
            {
                return this.planetSizeField;
            }
            set
            {
                this.planetSizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StarSystemTransformation
    {

        private SerializableVector3 positionField;

        private SerializableVector3 rotationField;

        private float scaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 Rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerializableVector3 : ValueType
    {

        private float xField;

        private float yField;

        private float zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Keyframe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SerializableQuaternion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SerializableVector3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValueType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Keyframe : ValueType
    {

        private float timeField;

        private float valueField;

        private float inTangentField;

        private float outTangentField;

        private int tangentModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float inTangent
        {
            get
            {
                return this.inTangentField;
            }
            set
            {
                this.inTangentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float outTangent
        {
            get
            {
                return this.outTangentField;
            }
            set
            {
                this.outTangentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tangentMode
        {
            get
            {
                return this.tangentModeField;
            }
            set
            {
                this.tangentModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerializableQuaternion : ValueType
    {

        private float xField;

        private float yField;

        private float zField;

        private float wField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float W
        {
            get
            {
                return this.wField;
            }
            set
            {
                this.wField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Shot))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemDiscoverySequenceDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Shot : DatatableElement
    {

        private CameraShotKeyDefinition[] keyField;

        private CameraAlterationDefinition[] itemsField;

        private double durationField;

        private float lateStartTimeRatioField;

        private float earlyEndTimeRatioField;

        private float lateEndTimeRatioField;

        public Shot()
        {
            this.lateStartTimeRatioField = ((float)(0F));
            this.earlyEndTimeRatioField = ((float)(1F));
            this.lateEndTimeRatioField = ((float)(1F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Key", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraShotKeyDefinition[] Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlterationAudio", typeof(CameraAlterationDefinition_Audio), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AlterationDamping", typeof(CameraAlterationDefinition_Damping), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AlterationEvent", typeof(CameraAlterationDefinition_Event), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AlterationFocus", typeof(CameraAlterationDefinition_Focus), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AlterationPlanetDestruction", typeof(CameraAlterationDefinition_PlanetDestruction), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("AlterationShake", typeof(CameraAlterationDefinition_Shake), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraAlterationDefinition[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float LateStartTimeRatio
        {
            get
            {
                return this.lateStartTimeRatioField;
            }
            set
            {
                this.lateStartTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float EarlyEndTimeRatio
        {
            get
            {
                return this.earlyEndTimeRatioField;
            }
            set
            {
                this.earlyEndTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float LateEndTimeRatio
        {
            get
            {
                return this.lateEndTimeRatioField;
            }
            set
            {
                this.lateEndTimeRatioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraShotKeyDefinition
    {

        private CameraTargetOffsetDefinition mainTargetOffsetField;

        private CameraTargetOffsetDefinition mainTargetToFollowOffsetField;

        private CameraTargetOffsetDefinition[] additionalTargetOffsetsField;

        private CameraTargetOffsetDefinition[] additionalTargetToFollowOffsetsField;

        private CameraTargetFilterDefinition targetFilterField;

        private CameraTargetFilterDefinition targetToFollowFilterField;

        private SerializableVector3 targetOffsetField;

        private SerializableVector3 targetToFollowOffsetField;

        private SerializableVector3 cameraLocalOffsetField;

        private SerializableVector3 cameraPositionField;

        private SerializableQuaternion cameraRotationField;

        private SerializableVector3 cameraEulerField;

        private SerializableVector3 upVectorField;

        private CameraShotKeyLayerTransitionDefinition_Curve[] transitionField;

        private float startTimeRatioField;

        private float fieldOfViewField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetOffsetDefinition MainTargetOffset
        {
            get
            {
                return this.mainTargetOffsetField;
            }
            set
            {
                this.mainTargetOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetOffsetDefinition MainTargetToFollowOffset
        {
            get
            {
                return this.mainTargetToFollowOffsetField;
            }
            set
            {
                this.mainTargetToFollowOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalTargetOffset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public CameraTargetOffsetDefinition[] AdditionalTargetOffsets
        {
            get
            {
                return this.additionalTargetOffsetsField;
            }
            set
            {
                this.additionalTargetOffsetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalTargetToFollowOffset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public CameraTargetOffsetDefinition[] AdditionalTargetToFollowOffsets
        {
            get
            {
                return this.additionalTargetToFollowOffsetsField;
            }
            set
            {
                this.additionalTargetToFollowOffsetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetFilterDefinition TargetFilter
        {
            get
            {
                return this.targetFilterField;
            }
            set
            {
                this.targetFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetFilterDefinition TargetToFollowFilter
        {
            get
            {
                return this.targetToFollowFilterField;
            }
            set
            {
                this.targetToFollowFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 TargetOffset
        {
            get
            {
                return this.targetOffsetField;
            }
            set
            {
                this.targetOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 TargetToFollowOffset
        {
            get
            {
                return this.targetToFollowOffsetField;
            }
            set
            {
                this.targetToFollowOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 CameraLocalOffset
        {
            get
            {
                return this.cameraLocalOffsetField;
            }
            set
            {
                this.cameraLocalOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 CameraPosition
        {
            get
            {
                return this.cameraPositionField;
            }
            set
            {
                this.cameraPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableQuaternion CameraRotation
        {
            get
            {
                return this.cameraRotationField;
            }
            set
            {
                this.cameraRotationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 CameraEuler
        {
            get
            {
                return this.cameraEulerField;
            }
            set
            {
                this.cameraEulerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 UpVector
        {
            get
            {
                return this.upVectorField;
            }
            set
            {
                this.upVectorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LayerTransition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public CameraShotKeyLayerTransitionDefinition_Curve[] Transition
        {
            get
            {
                return this.transitionField;
            }
            set
            {
                this.transitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float StartTimeRatio
        {
            get
            {
                return this.startTimeRatioField;
            }
            set
            {
                this.startTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FieldOfView
        {
            get
            {
                return this.fieldOfViewField;
            }
            set
            {
                this.fieldOfViewField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraTargetOffsetDefinition
    {

        private CameraTargetFilterDefinition targetFilterField;

        private SerializableVector3 targetOffsetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetFilterDefinition TargetFilter
        {
            get
            {
                return this.targetFilterField;
            }
            set
            {
                this.targetFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 TargetOffset
        {
            get
            {
                return this.targetOffsetField;
            }
            set
            {
                this.targetOffsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraTargetFilterDefinition
    {

        private CameraTargetSelectionMethodDefinition[] itemsField;

        private Prerequisite[] items1Field;

        private EncounterEntityFilterDefinition parentEntityFilterField;

        private SubEntityFilterDefinition subEntityFilterField;

        private bool attachedToTargetField;

        private bool lookAtTargetPositionAlterationField;

        private bool ignoreTargetStatusField;

        public CameraTargetFilterDefinition()
        {
            this.attachedToTargetField = false;
            this.lookAtTargetPositionAlterationField = false;
            this.ignoreTargetStatusField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionMethod_EncounterEntity", typeof(CameraTargetSelectionMethodDefinition_EncounterEntity), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SelectionMethod_Name", typeof(CameraTargetSelectionMethodDefinition_Name), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CameraTargetSelectionMethodDefinition[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EncounterEntityFilterDefinition ParentEntityFilter
        {
            get
            {
                return this.parentEntityFilterField;
            }
            set
            {
                this.parentEntityFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SubEntityFilterDefinition SubEntityFilter
        {
            get
            {
                return this.subEntityFilterField;
            }
            set
            {
                this.subEntityFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AttachedToTarget
        {
            get
            {
                return this.attachedToTargetField;
            }
            set
            {
                this.attachedToTargetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LookAtTargetPositionAlteration
        {
            get
            {
                return this.lookAtTargetPositionAlterationField;
            }
            set
            {
                this.lookAtTargetPositionAlterationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreTargetStatus
        {
            get
            {
                return this.ignoreTargetStatusField;
            }
            set
            {
                this.ignoreTargetStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraTargetSelectionMethodDefinition_EncounterEntity : CameraTargetSelectionMethodDefinition
    {

        private EncounterEventEntityRole eventEntityRoleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EncounterEventEntityRole EventEntityRole
        {
            get
            {
                return this.eventEntityRoleField;
            }
            set
            {
                this.eventEntityRoleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum EncounterEventEntityRole
    {

        /// <remarks/>
        Initiator,

        /// <remarks/>
        Target,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraTargetSelectionMethodDefinition_Name))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraTargetSelectionMethodDefinition_EncounterEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraTargetSelectionMethodDefinition
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraTargetSelectionMethodDefinition_Name : CameraTargetSelectionMethodDefinition
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterpreterPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathPrerequisite))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterpreterPrerequisite))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Prerequisite
    {

        private bool invertedField;

        private string flagsField;

        private string valueField;

        public Prerequisite()
        {
            this.invertedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Inverted
        {
            get
            {
                return this.invertedField;
            }
            set
            {
                this.invertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathPrerequisite : Prerequisite
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncounterEntityFilterDefinition
    {

        private Prerequisite[] itemsField;

        private EncounterEntityType entityTypeField;

        private EncounterEntityTags entityTagsField;

        public EncounterEntityFilterDefinition()
        {
            this.entityTypeField = EncounterEntityType.Undefined;
            this.entityTagsField = EncounterEntityTags.None;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpreterPrerequisite", typeof(InterpreterPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PathPrerequisite", typeof(PathPrerequisite), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prerequisite[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EncounterEntityType.Undefined)]
        public EncounterEntityType EntityType
        {
            get
            {
                return this.entityTypeField;
            }
            set
            {
                this.entityTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EncounterEntityTags.None)]
        public EncounterEntityTags EntityTags
        {
            get
            {
                return this.entityTagsField;
            }
            set
            {
                this.entityTagsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum EncounterEntityType
    {

        /// <remarks/>
        Arena,

        /// <remarks/>
        EffectArea,

        /// <remarks/>
        Group,

        /// <remarks/>
        Flotilla,

        /// <remarks/>
        Ship,

        /// <remarks/>
        ShipSection,

        /// <remarks/>
        Module,

        /// <remarks/>
        Salvo,

        /// <remarks/>
        Citadel,

        /// <remarks/>
        CitadelModule,

        /// <remarks/>
        CitadelSalvo,

        /// <remarks/>
        Undefined,
    }

    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum EncounterEntityTags
    {

        /// <remarks/>
        None = 1,

        /// <remarks/>
        Me = 2,

        /// <remarks/>
        Other = 4,

        /// <remarks/>
        SameShip = 8,

        /// <remarks/>
        OtherShip = 16,

        /// <remarks/>
        SameFlotilla = 32,

        /// <remarks/>
        OtherFlotilla = 64,

        /// <remarks/>
        SameGroup = 128,

        /// <remarks/>
        OtherGroup = 256,

        /// <remarks/>
        EffectInitiator = 512,

        /// <remarks/>
        EffectTarget = 1024,

        /// <remarks/>
        Alive = 2048,

        /// <remarks/>
        Deactivated = 4096,

        /// <remarks/>
        Destroyed = 8192,

        /// <remarks/>
        SameModule = 16384,

        /// <remarks/>
        OtherModule = 32768,

        /// <remarks/>
        Arena = 65536,

        /// <remarks/>
        Reinforcement = 131072,

        /// <remarks/>
        Inactive = 262144,

        /// <remarks/>
        MyMainTarget = 524288,

        /// <remarks/>
        SameCitadel = 1048576,

        /// <remarks/>
        OtherCitadel = 2097152,

        /// <remarks/>
        SameCitadelModule = 4194304,

        /// <remarks/>
        OtherCitadelModule = 8388608,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubEntityFilterDefinition
    {

        private EncounterEntityFilterDefinition subEntityFilterField;

        private SubEntitySelectionMethodEnum subEntitySelectionMethodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EncounterEntityFilterDefinition SubEntityFilter
        {
            get
            {
                return this.subEntityFilterField;
            }
            set
            {
                this.subEntityFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubEntitySelectionMethodEnum SubEntitySelectionMethod
        {
            get
            {
                return this.subEntitySelectionMethodField;
            }
            set
            {
                this.subEntitySelectionMethodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SubEntitySelectionMethodEnum
    {

        /// <remarks/>
        First,

        /// <remarks/>
        Random,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraShotKeyLayerTransitionDefinition_Curve : CameraShotKeyLayerTransitionDefinition
    {

        private AnimationCurve curveField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AnimationCurve Curve
        {
            get
            {
                return this.curveField;
            }
            set
            {
                this.curveField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnimationCurve
    {

        private Keyframe[] keysField;

        private WrapMode preWrapModeField;

        private WrapMode postWrapModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Keyframe[] keys
        {
            get
            {
                return this.keysField;
            }
            set
            {
                this.keysField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WrapMode preWrapMode
        {
            get
            {
                return this.preWrapModeField;
            }
            set
            {
                this.preWrapModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WrapMode postWrapMode
        {
            get
            {
                return this.postWrapModeField;
            }
            set
            {
                this.postWrapModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum WrapMode
    {

        /// <remarks/>
        Default,

        /// <remarks/>
        Clamp,

        /// <remarks/>
        Once,

        /// <remarks/>
        Loop,

        /// <remarks/>
        PingPong,

        /// <remarks/>
        ClampForever,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraShotKeyLayerTransitionDefinition_Curve))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraShotKeyLayerTransitionDefinition
    {

        private float startTimeRatioField;

        private CameraShotKeyTransitionLayerTags layerTagsField;

        private CameraShotKeyTransitionLayerOptions layerOptionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float StartTimeRatio
        {
            get
            {
                return this.startTimeRatioField;
            }
            set
            {
                this.startTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CameraShotKeyTransitionLayerTags LayerTags
        {
            get
            {
                return this.layerTagsField;
            }
            set
            {
                this.layerTagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CameraShotKeyTransitionLayerOptions LayerOptions
        {
            get
            {
                return this.layerOptionsField;
            }
            set
            {
                this.layerOptionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CameraShotKeyTransitionLayerTags
    {

        /// <remarks/>
        None = 1,

        /// <remarks/>
        Position = 2,

        /// <remarks/>
        Rotation = 4,

        /// <remarks/>
        FieldOfView = 8,

        /// <remarks/>
        All = 16,
    }

    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CameraShotKeyTransitionLayerOptions
    {

        /// <remarks/>
        None = 1,

        /// <remarks/>
        SphericalRotation = 2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_Audio : CameraAlterationDefinition
    {

        private string startEventNameField;

        private string endEventNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartEventName
        {
            get
            {
                return this.startEventNameField;
            }
            set
            {
                this.startEventNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndEventName
        {
            get
            {
                return this.endEventNameField;
            }
            set
            {
                this.endEventNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_Shake))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_Damping))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_Focus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_Audio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_Event))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraAlterationDefinition_PlanetDestruction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition
    {

        private float startTimeRatioField;

        private float endTimeRatioField;

        private int priorityField;

        private bool timeRatiosBasedOnTheoreticalDurationField;

        public CameraAlterationDefinition()
        {
            this.priorityField = 0;
            this.timeRatiosBasedOnTheoreticalDurationField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float StartTimeRatio
        {
            get
            {
                return this.startTimeRatioField;
            }
            set
            {
                this.startTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndTimeRatio
        {
            get
            {
                return this.endTimeRatioField;
            }
            set
            {
                this.endTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TimeRatiosBasedOnTheoreticalDuration
        {
            get
            {
                return this.timeRatiosBasedOnTheoreticalDurationField;
            }
            set
            {
                this.timeRatiosBasedOnTheoreticalDurationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_Shake : CameraAlterationDefinition
    {

        private float amplitudeMinField;

        private float amplitudeMaxField;

        private float smoothnessField;

        private float frequencyMinField;

        private float frequencyMaxField;

        public CameraAlterationDefinition_Shake()
        {
            this.amplitudeMinField = ((float)(0F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float AmplitudeMin
        {
            get
            {
                return this.amplitudeMinField;
            }
            set
            {
                this.amplitudeMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AmplitudeMax
        {
            get
            {
                return this.amplitudeMaxField;
            }
            set
            {
                this.amplitudeMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Smoothness
        {
            get
            {
                return this.smoothnessField;
            }
            set
            {
                this.smoothnessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FrequencyMin
        {
            get
            {
                return this.frequencyMinField;
            }
            set
            {
                this.frequencyMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FrequencyMax
        {
            get
            {
                return this.frequencyMaxField;
            }
            set
            {
                this.frequencyMaxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_Damping : CameraAlterationDefinition
    {

        private float dampingDurationField;

        private float amplificationEndTimeRatioField;

        private float reductionStartTimeRatioField;

        public CameraAlterationDefinition_Damping()
        {
            this.amplificationEndTimeRatioField = ((float)(0F));
            this.reductionStartTimeRatioField = ((float)(1F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DampingDuration
        {
            get
            {
                return this.dampingDurationField;
            }
            set
            {
                this.dampingDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float AmplificationEndTimeRatio
        {
            get
            {
                return this.amplificationEndTimeRatioField;
            }
            set
            {
                this.amplificationEndTimeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float ReductionStartTimeRatio
        {
            get
            {
                return this.reductionStartTimeRatioField;
            }
            set
            {
                this.reductionStartTimeRatioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_Focus : CameraAlterationDefinition
    {

        private int indexField;

        public CameraAlterationDefinition_Focus()
        {
            this.indexField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_Event : CameraAlterationDefinition
    {

        private int startEventIndexField;

        private int endEventIndexField;

        public CameraAlterationDefinition_Event()
        {
            this.startEventIndexField = 0;
            this.endEventIndexField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int StartEventIndex
        {
            get
            {
                return this.startEventIndexField;
            }
            set
            {
                this.startEventIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int EndEventIndex
        {
            get
            {
                return this.endEventIndexField;
            }
            set
            {
                this.endEventIndexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraAlterationDefinition_PlanetDestruction : CameraAlterationDefinition
    {

        private Type eventTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Type EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum Type
    {

        /// <remarks/>
        SpawnWeapon,

        /// <remarks/>
        LaunchShot,

        /// <remarks/>
        LaunchImpactOnSolidPlanet,

        /// <remarks/>
        LaunchImpactOnGasPlanet,

        /// <remarks/>
        MorphPlanet,

        /// <remarks/>
        SwitchPlanet,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShipTransformation
    {

        private SerializableVector3 positionField;

        private SerializableVector3 rotationField;

        private string nameField;

        private int selectorIndexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 Rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SelectorIndex
        {
            get
            {
                return this.selectorIndexField;
            }
            set
            {
                this.selectorIndexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlanetTransformation
    {

        private SerializableVector3 revolutionAnglesField;

        private SerializableVector3 positionAnglesField;

        private float orbitDistanceField;

        private float radiusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 RevolutionAngles
        {
            get
            {
                return this.revolutionAnglesField;
            }
            set
            {
                this.revolutionAnglesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 PositionAngles
        {
            get
            {
                return this.positionAnglesField;
            }
            set
            {
                this.positionAnglesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OrbitDistance
        {
            get
            {
                return this.orbitDistanceField;
            }
            set
            {
                this.orbitDistanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Radius
        {
            get
            {
                return this.radiusField;
            }
            set
            {
                this.radiusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class SystemDiscoverySequenceDefinition : DatatableElement
    {

        private PlanetTransformation[] planetTransformationField;

        private PlanetTransformation[] galaxyPlanetTransformationField;

        private ShipTransformation[] shipTransformationField;

        private Shot[] shotField;

        private StarSystemTransformation starSystemTransformField;

        private SerializableVector3 galaxyCameraPositionField;

        private SerializableVector3 galaxyCameraEulerAnglesField;

        private PlanetoidRadiusFromPlanetSize[] planetoidRadiusFromPlanetSizeField;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlanetTransformation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PlanetTransformation[] PlanetTransformation
        {
            get
            {
                return this.planetTransformationField;
            }
            set
            {
                this.planetTransformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GalaxyPlanetTransformation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PlanetTransformation[] GalaxyPlanetTransformation
        {
            get
            {
                return this.galaxyPlanetTransformationField;
            }
            set
            {
                this.galaxyPlanetTransformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipTransformation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipTransformation[] ShipTransformation
        {
            get
            {
                return this.shipTransformationField;
            }
            set
            {
                this.shipTransformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Shot", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Shot[] Shot
        {
            get
            {
                return this.shotField;
            }
            set
            {
                this.shotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StarSystemTransformation StarSystemTransform
        {
            get
            {
                return this.starSystemTransformField;
            }
            set
            {
                this.starSystemTransformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 GalaxyCameraPosition
        {
            get
            {
                return this.galaxyCameraPositionField;
            }
            set
            {
                this.galaxyCameraPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SerializableVector3 GalaxyCameraEulerAngles
        {
            get
            {
                return this.galaxyCameraEulerAnglesField;
            }
            set
            {
                this.galaxyCameraEulerAnglesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlanetoidRadiusFromPlanetSize", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PlanetoidRadiusFromPlanetSize[] PlanetoidRadiusFromPlanetSize
        {
            get
            {
                return this.planetoidRadiusFromPlanetSizeField;
            }
            set
            {
                this.planetoidRadiusFromPlanetSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
    }
}