//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace EndlessModding.EndlessSpace2.Common.Classes.TechnologyGelperVariableDefinition
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyHelperVariableDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyHelperOperation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyHelperOperationInt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyHelperOperationValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnologyHelperOperationRefinedProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyHelperOperationItem
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyHelperOperation : TechnologyHelperOperationItem
    {

        private TechnologyHelperOperationItem[] itemsField;

        private OperatorType operatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Int", typeof(TechnologyHelperOperationInt), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Operation", typeof(TechnologyHelperOperation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("RefinedProperty", typeof(TechnologyHelperOperationRefinedProperty), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(TechnologyHelperOperationValue), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechnologyHelperOperationItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OperatorType Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyHelperOperationInt : TechnologyHelperOperationItem
    {

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyHelperOperationRefinedProperty : TechnologyHelperOperationItem
    {

        private PropertyType propertyField;

        private int resourceIndexField;

        public TechnologyHelperOperationRefinedProperty()
        {
            this.resourceIndexField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PropertyType Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int ResourceIndex
        {
            get
            {
                return this.resourceIndexField;
            }
            set
            {
                this.resourceIndexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PropertyType
    {

        /// <remarks/>
        HighestTechnologyTurns,

        /// <remarks/>
        AveragePopulationTurns,

        /// <remarks/>
        AverageImprovementsTurns,

        /// <remarks/>
        AverageHappiness,

        /// <remarks/>
        AverageFullness,

        /// <remarks/>
        ProportionalTurns,

        /// <remarks/>
        AverageAvailableStarSystemImprovementsCount,

        /// <remarks/>
        HasStrategic,

        /// <remarks/>
        HasLuxury,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TechnologyHelperOperationValue : TechnologyHelperOperationItem
    {

        private SourceType sourceField;

        private string pathField;

        private string propertyNameField;

        private float multiplierField;

        public TechnologyHelperOperationValue()
        {
            this.multiplierField = ((float)(1F));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SourceType Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float Multiplier
        {
            get
            {
                return this.multiplierField;
            }
            set
            {
                this.multiplierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SourceType
    {

        /// <remarks/>
        Empire,

        /// <remarks/>
        KnownEmpires,

        /// <remarks/>
        AllEmpires,

        /// <remarks/>
        VisibleSystems,

        /// <remarks/>
        OwnedSystems,

        /// <remarks/>
        NeutralSystems,

        /// <remarks/>
        AllSystems,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OperatorType
    {

        /// <remarks/>
        Addition,

        /// <remarks/>
        Subtraction,

        /// <remarks/>
        Multiplication,

        /// <remarks/>
        Division,

        /// <remarks/>
        Min,

        /// <remarks/>
        Max,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class TechnologyHelperVariableDefinition : DatatableElement
    {

        private TechnologyHelperOperationItem[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Int", typeof(TechnologyHelperOperationInt), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Operation", typeof(TechnologyHelperOperation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("RefinedProperty", typeof(TechnologyHelperOperationRefinedProperty), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(TechnologyHelperOperationValue), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechnologyHelperOperationItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}